title: IMGeo objectenhandboek b√®ta
lang: nl
description: Praktijkhandleiding voor toepassing van de BGT|IMGeo standaarden bij de objectafbakening

#readme_index:
#  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-breadcrumbs
  - jekyll-archives
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  
remote_theme: rundocs/jekyll-rtd-theme
